using System.Buffers.Text;
using System.Security.Cryptography;
using System.Text;

namespace WaterService.Configuration;

/// <summary>
/// Unwraps individually-encrypted configuration values, mirroring the Java <c>SecretCodec</c>.
///
/// <para>A value in a <c>.env</c> file (or a real environment variable) may be stored as
/// <c>enc:v1:&lt;base64url(nonce || ciphertext || tag)&gt;</c> instead of plaintext. Anything without that
/// marker is returned untouched, so a partially-encrypted file is valid and the migration can be done
/// one key at a time — and, critically, a service carrying this codec still starts against the old
/// fully-plaintext file.</para>
///
/// <para><strong>Algorithm:</strong> AES-256-GCM with a 12-byte random nonce and a 128-bit tag. The
/// variable's own name is bound in as additional authenticated data, so a ciphertext lifted from
/// <c>DB_USERNAME</c> fails to decrypt if pasted over <c>DB_PASSWORD</c>. Wire-compatible with
/// <c>efj-backend/secret/Protect-Env.ps1</c> and the Java services, so one encrypted <c>.env</c> file
/// serves all of them.</para>
///
/// <para><strong>Key material</strong> comes from <c>FF_MASTER_KEY_FILE</c> (a path — preferred, so the
/// key never lands in <c>docker inspect</c>, shell history, or <c>/proc/self/environ</c>) or, as a
/// fallback, the raw <c>FF_MASTER_KEY</c> variable. Either form accepts 32 bytes as hex or base64,
/// with any whitespace ignored.</para>
///
/// <para>A missing or wrong key when an encrypted value is actually present is a <em>hard startup
/// failure</em>, never a silent pass-through: handing an untouched <c>enc:v1:...</c> string to the
/// SqlClient driver would surface as a baffling login error far from the real cause.</para>
/// </summary>
public static class SecretCodec
{
    /// <summary>Marker identifying an encrypted value; version-tagged so the format can change later.</summary>
    internal const string Prefix = "enc:v1:";

    private const string KeyFileEnv = "FF_MASTER_KEY_FILE";
    private const string KeyEnv = "FF_MASTER_KEY";

    private const int KeyBytes = 32;
    private const int NonceBytes = 12;
    private const int TagBytes = 16; // 128-bit GCM tag

    private static readonly Lock KeyLock = new();

    /// <summary>Cached so a file-backed key is read once per process rather than once per value.</summary>
    private static byte[]? _cachedKey;

    /// <summary>
    /// Reports whether a value carries the encryption marker.
    /// </summary>
    public static bool IsEncrypted(string? value) =>
        value is not null && value.StartsWith(Prefix, StringComparison.Ordinal);

    /// <summary>
    /// Returns the plaintext for a value, decrypting it when it carries the <c>enc:v1:</c> marker and
    /// returning it verbatim when it does not.
    /// </summary>
    /// <param name="name">the variable name, bound in as additional authenticated data</param>
    /// <param name="value">the raw value</param>
    /// <exception cref="InvalidOperationException">
    /// The value is encrypted but no usable key is configured, or the payload is malformed, tampered
    /// with, or from another key.
    /// </exception>
    public static string? DecryptIfNeeded(string name, string? value) =>
        IsEncrypted(value) ? DecryptWith(RequireKey(name), name, value!) : value;

    /// <summary>
    /// Returns the plaintext of every <c>enc:v1:</c> value sitting in the real process environment.
    ///
    /// <para>Needed because credentials do not always arrive through the dotenv file: a container
    /// deployed with Docker's <c>--env-file</c> has them injected as genuine environment variables that
    /// <see cref="DotEnvLoader"/> never sees. Returns an empty map when nothing in the environment is
    /// encrypted, which keeps this a complete no-op for the existing all-plaintext deployments.</para>
    /// </summary>
    public static IReadOnlyDictionary<string, string?> DecryptEnvironmentVariables()
    {
        var decrypted = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);

        foreach (System.Collections.DictionaryEntry entry in Environment.GetEnvironmentVariables())
        {
            if (entry.Key is string name && entry.Value is string value && IsEncrypted(value))
            {
                decrypted[name] = DecryptIfNeeded(name, value);
            }
        }

        return decrypted;
    }

    /// <summary>
    /// Decrypts a marked value with an explicitly supplied key.
    ///
    /// <para>Split out from <see cref="DecryptIfNeeded"/> so the cipher can be exercised in tests
    /// against a known key and a fixture generated by <c>secret/Protect-Env.ps1</c>: the
    /// environment-backed key lookup is process-wide and cached, so it cannot be driven from a test.</para>
    /// </summary>
    internal static string DecryptWith(byte[] key, string name, string value)
    {
        byte[] payload;
        try
        {
            payload = Base64Url.DecodeFromChars(value.AsSpan(Prefix.Length));
        }
        catch (FormatException e)
        {
            throw new InvalidOperationException(
                $"Value of {name} is marked {Prefix} but is not valid base64url.", e);
        }

        if (payload.Length < NonceBytes + TagBytes)
        {
            throw new InvalidOperationException(
                $"Value of {name} is marked {Prefix} but is too short to be a valid payload.");
        }

        // Java/PowerShell emit nonce || ciphertext || tag; .NET's AesGcm takes the three parts separately.
        ReadOnlySpan<byte> span = payload;
        ReadOnlySpan<byte> nonce = span[..NonceBytes];
        ReadOnlySpan<byte> ciphertext = span[NonceBytes..^TagBytes];
        ReadOnlySpan<byte> tag = span[^TagBytes..];

        byte[] plaintext = new byte[ciphertext.Length];
        try
        {
            using var gcm = new AesGcm(key, TagBytes);
            gcm.Decrypt(nonce, ciphertext, tag, plaintext, Encoding.UTF8.GetBytes(name));
            return Encoding.UTF8.GetString(plaintext);
        }
        catch (Exception e)
        {
            // Deliberately vague about the cause and silent about the value: a GCM tag failure means
            // wrong key, wrong variable name, or tampering, and distinguishing them helps an attacker.
            throw new InvalidOperationException(
                $"Could not decrypt {name}. The master key does not match the value, "
                + "or the value was altered.", e);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(plaintext);
        }
    }

    /// <summary>
    /// Loads and caches the master key.
    /// </summary>
    /// <param name="name">the variable being decrypted, used only to make the failure message actionable</param>
    /// <exception cref="InvalidOperationException">No key is configured, or the material is not 32 bytes.</exception>
    private static byte[] RequireKey(string name)
    {
        byte[]? key = Volatile.Read(ref _cachedKey);
        if (key is not null)
        {
            return key;
        }

        lock (KeyLock)
        {
            if (_cachedKey is not null)
            {
                return _cachedKey;
            }

            string? material = ReadKeyMaterial();
            if (material is null)
            {
                throw new InvalidOperationException(
                    $"Value of {name} is encrypted but no master key is configured. Set "
                    + $"{KeyFileEnv} to the key file path (preferred) or {KeyEnv}.");
            }

            byte[] bytes = DecodeKeyMaterial(material);
            if (bytes.Length != KeyBytes)
            {
                throw new InvalidOperationException(
                    $"Master key must be {KeyBytes} bytes (64 hex chars or 44 base64 chars); got "
                    + $"{bytes.Length} bytes.");
            }

            _cachedKey = bytes;
            return bytes;
        }
    }

    /// <summary>
    /// Reads key material from the key file when configured, otherwise from the raw environment variable.
    /// </summary>
    /// <returns>the undecoded key material, or <c>null</c> when neither source is configured</returns>
    private static string? ReadKeyMaterial()
    {
        string? keyFile = Environment.GetEnvironmentVariable(KeyFileEnv);
        if (!string.IsNullOrWhiteSpace(keyFile))
        {
            string path = keyFile.Trim();
            try
            {
                return File.ReadAllText(path, Encoding.UTF8);
            }
            catch (Exception e)
            {
                throw new InvalidOperationException(
                    $"Could not read the master key file at {path} (from {KeyFileEnv}).", e);
            }
        }

        string? inline = Environment.GetEnvironmentVariable(KeyEnv);
        return string.IsNullOrWhiteSpace(inline) ? null : inline;
    }

    /// <summary>
    /// Decodes key material given as hex or base64, ignoring whitespace and line breaks so a
    /// human-formatted key file works as-is.
    /// </summary>
    private static byte[] DecodeKeyMaterial(string material)
    {
        string compact = new(material.Where(c => !char.IsWhiteSpace(c)).ToArray());

        if (compact.Length == KeyBytes * 2 && compact.All(char.IsAsciiHexDigit))
        {
            return Convert.FromHexString(compact);
        }

        try
        {
            return Convert.FromBase64String(compact);
        }
        catch (FormatException e)
        {
            throw new InvalidOperationException(
                $"Master key material is neither {KeyBytes * 2} hex characters nor valid base64.", e);
        }
    }
}
